# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\2022-Daftar\PyQt\Babel\bin\gui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2016, 1427)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.wordlist = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wordlist.sizePolicy().hasHeightForWidth())
        self.wordlist.setSizePolicy(sizePolicy)
        self.wordlist.setMinimumSize(QtCore.QSize(300, 0))
        self.wordlist.setObjectName("wordlist")
        self.horizontalLayout.addWidget(self.wordlist)
        self.lexBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.lexBrowser.setObjectName("lexBrowser")
        self.horizontalLayout.addWidget(self.lexBrowser)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2016, 52))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuLexicon = QtWidgets.QMenu(self.menubar)
        self.menuLexicon.setObjectName("menuLexicon")
        self.menuSort = QtWidgets.QMenu(self.menuLexicon)
        self.menuSort.setObjectName("menuSort")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAdd = QtWidgets.QAction(MainWindow)
        self.actionAdd.setObjectName("actionAdd")
        self.actionRemove = QtWidgets.QAction(MainWindow)
        self.actionRemove.setObjectName("actionRemove")
        self.actionModify = QtWidgets.QAction(MainWindow)
        self.actionModify.setObjectName("actionModify")
        self.actionSortAlphabet = QtWidgets.QAction(MainWindow)
        self.actionSortAlphabet.setObjectName("actionSortAlphabet")
        self.actionSortPOS = QtWidgets.QAction(MainWindow)
        self.actionSortPOS.setObjectName("actionSortPOS")
        self.actionPOSView = QtWidgets.QAction(MainWindow)
        self.actionPOSView.setObjectName("actionPOSView")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addAction(self.actionExit)
        self.menuSort.addAction(self.actionSortAlphabet)
        self.menuSort.addAction(self.actionSortPOS)
        self.menuLexicon.addAction(self.actionAdd)
        self.menuLexicon.addAction(self.actionRemove)
        self.menuLexicon.addAction(self.actionModify)
        self.menuLexicon.addAction(self.menuSort.menuAction())
        self.menuView.addAction(self.actionPOSView)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuLexicon.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Babel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuLexicon.setTitle(_translate("MainWindow", "Lexicon"))
        self.menuSort.setTitle(_translate("MainWindow", "Sort"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSaveAs.setText(_translate("MainWindow", "Save as"))
        self.actionSaveAs.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAdd.setText(_translate("MainWindow", "Add"))
        self.actionAdd.setShortcut(_translate("MainWindow", "Ctrl+`"))
        self.actionRemove.setText(_translate("MainWindow", "Remove"))
        self.actionRemove.setShortcut(_translate("MainWindow", "Del"))
        self.actionModify.setText(_translate("MainWindow", "Modify"))
        self.actionModify.setShortcut(_translate("MainWindow", "Ctrl+="))
        self.actionSortAlphabet.setText(_translate("MainWindow", "Alphabet"))
        self.actionSortPOS.setText(_translate("MainWindow", "Part of Speech"))
        self.actionPOSView.setText(_translate("MainWindow", "Part of Speech"))

